[build]
  command = "npm install"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/societies/test-content"
  to = "/.netlify/functions/societies"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/societies"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
